framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
#        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
#            failed: 'doctrine://default?queue_name=failed'
#            sync: 'sync://'
            async_teste:
                dsn: '%env(MESSENGER_TRANSPORT_DSN1)%'
                options:
                    exchange:
                        name: 'teste'

        #
        routing:
            # Route your messages to the transports
            App\Infrastructure\Message\SendNotificationMessage: async
            App\Infrastructure\Teste\TesteQueue: async_teste


## when@test:W
##    framework:
##        messenger:
##            transports:
##                # replace with your transport name here (e.g., my_transport: 'in-memory://')
##                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
##                async: 'in-memory://'
