name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@v2
        with:
          server: ${{ secrets.EC2_SERVER }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: 'cd /home/ubuntu/var/www/booking-api && git pull && composer install --no-dev --optimize-autoloader && php bin/console cache:clear && php bin/console doctrine:migrations:migrate --no-interaction'